image: treehouses/couchdb:latest
manifests:
  -
    image: treehouses/rpi-couchdb:2.1.1
    platform:
      architecture: arm
      os: linux
  -
    image: treehouses/arm64-rpi-couchdb:2.1.1
    platform:
      architecture: arm64
      os: linux
  -
    image: amd64/couchdb:2.1.1
    platform:
      architecture: amd64
      os: linux
